openapi: 3.0.0
info:
  title: Book Management API
  version: 1.0.0
  description: API for managing books, including image uploads

servers:
  - url: http://localhost:5000/api

paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: List of books
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                isbn:
                  type: string
                publishedYear:
                  type: integer
                description:
                  type: string
                rating:
                  type: number
                reviews:
                  type: integer
                genres:
                  type: array
                  items:
                    type: string
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Book created successfully

  /books/{id}:
    get:
      summary: Get a single book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Book found
        '404':
          description: Book not found

    put:
      summary: Update an existing book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                isbn:
                  type: string
                publishedYear:
                  type: integer
                description:
                  type: string
                rating:
                  type: number
                reviews:
                  type: integer
                genres:
                  type: array
                  items:
                    type: string
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Book updated
        '404':
          description: Book not found

    delete:
      summary: Delete a book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Book deleted
        '404':
          description: Book not found
