name: Keploy API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./backend/mongoDB
        run: npm install

      - name: Start server
        working-directory: ./backend/mongoDB
        run: |
          npm start &
          sleep 10  # Wait for API to be ready

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Tests
        env:
          KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
        run: |
          keploy test-suite \
            --app=0dd7ad67-0fa6-4c35-9690-392a802518bd \
            --base-path=http://localhost:5000/api/books \
            --cloud
